services:
  - type: web
    name: clickstream-backend
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn clickstream_project.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
